name = "streamdeck-cf-blog-rss"
type = "javascript"
workers_dev = false
compatibility_date = "2021-10-02"

zone_id = "da25af1c9238d4dd7c4bc7ae268ecbf1"
routes = ["streamdeck-cf-blog-rss.eidam.cf"]

kv_namespaces = [ 
  { binding = "KV_STREAMDECK", id = "b700d11cb9d84edba0fa26babcedd7bd" }
]

[durable_objects]
classes = [
  { binding = "DO_STREAMDECK", class_name = "StreamDeckDurableObject" },
]

[triggers]
crons = ["* * * * *"]

[build]
command = "yarn install && yarn build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "modules"
main = "main.mjs"
